### ISSUE TITLE
Review onchain documentation to be uppdated

### ISSUE THREAD

**Issue by michele-nuzzi** [HarmonicLabs/plu-ts-docs#21]

**Comment by amnambiar** [comment]
Raised PR in review

**Comment by michele-nuzzi** [comment]
from here we can proceed updating the missing parts

**Comment by amnambiar** [comment]
@michele-nuzzi ,

Raised draft PR https://github.com/HarmonicLabs/plu-ts-docs/pull/28, with [V1 version updates](https://github.com/HarmonicLabs/plu-ts-docs/pull/28/commits/f15946ed85f0814489b0a3dfbf9aeab28de2bc5a), for initial review.

**Comment by amnambiar** [comment]
@michele-nuzzi  PR [#28](https://github.com/HarmonicLabs/plu-ts-docs/pull/28) with all V1, V2, V3 updates are ready for review. 

This however needs update on specifically deprecated items in V1 or V2.

**Comment by amnambiar** [comment]
Build issue fixes are in PR https://github.com/HarmonicLabs/plu-ts-docs/pull/30
